// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4HJNCKTMOlws1mxjudC887L4HsjYCq8',
    appId: '1:800176112724:web:564199f276634482e619c1',
    messagingSenderId: '800176112724',
    projectId: 'authx-31062',
    authDomain: 'authx-31062.firebaseapp.com',
    storageBucket: 'authx-31062.appspot.com',
    measurementId: 'G-PV5YY1W5DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComNytt_YTbq2_GYdCtdH2BRhzCIPDp1I',
    appId: '1:800176112724:android:7bf9cf8452518b38e619c1',
    messagingSenderId: '800176112724',
    projectId: 'authx-31062',
    storageBucket: 'authx-31062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2bPCh3f-k3GzD8LNToGUNyCRmI_kIQEw',
    appId: '1:800176112724:ios:3bb93f3ed208a3c8e619c1',
    messagingSenderId: '800176112724',
    projectId: 'authx-31062',
    storageBucket: 'authx-31062.appspot.com',
    iosBundleId: 'com.example.xyz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2bPCh3f-k3GzD8LNToGUNyCRmI_kIQEw',
    appId: '1:800176112724:ios:3bb93f3ed208a3c8e619c1',
    messagingSenderId: '800176112724',
    projectId: 'authx-31062',
    storageBucket: 'authx-31062.appspot.com',
    iosBundleId: 'com.example.xyz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn4HJNCKTMOlws1mxjudC887L4HsjYCq8',
    appId: '1:800176112724:web:7338096e12f0619ee619c1',
    messagingSenderId: '800176112724',
    projectId: 'authx-31062',
    authDomain: 'authx-31062.firebaseapp.com',
    storageBucket: 'authx-31062.appspot.com',
    measurementId: 'G-1W8Z2BNC0Z',
  );
}
